### ISSUE TITLE
Nothing happens when click the runcat.exe！

### ISSUE THREAD

**Issue by ChenMathilda** [Kyome22/RunCat_for_windows#70]
Nothing happens when clicking the exe file both two computers.
My OS is Windows 10.
Changed the compatibility, it didn't work;
Trying to run as an administrator still didn't work.

**Comment by AirBashX** [comment]
me too
win11同样没有反应,RunCat_with_.NET5.0.zip版本,没法运行,点击后没有反应

**Comment by kelvinchin12070811** [comment]
Same problem, I get the exception said "System.InvalidOperationException: 'Cannot load Counter Name data because an invalid index '' was read from the registry.'" while trying to build the application by my self

This stackoverflow thread solved my problem btw
[https://stackoverflow.com/a/35909225/6717814](https://stackoverflow.com/a/35909225/6717814)

**Comment by ChenMathilda** [comment]
> me too win11同样没有反应,RunCat_with_.NET5.0.zip版本,没法运行,点击后没有反应
快去看这个回答，用1.9版本
